/**
 * Created by frank.zhang on 5/5/15.
 */
app.controller('fanCtrl', ['$scope', function ($scope) {
    $scope.list=[
        {
            'month':'一月',
            'title':'摩羯'
        },
        {
            'month':'二月',
            'title':'水瓶'
        },
        {
            'month':'三月',
            'title':'双鱼'
        },
        {
            'month':'四月',
            'title':'白羊'
        },
        {
            'month':'五月',
            'title':'金牛'
        },
        {
            'month':'六月',
            'title':'双子'
        },
        {
            'month':'七月',
            'title':'巨蟹'
        },
        {
            'month':'八月',
            'title':'狮子'
        },
        {
            'month':'九月',
            'title':'处女'
        },
        {
            'month':'十月',
            'title':'天平'
        },
        {
            'month':'十一月',
            'title':'天蝎'
        },
        {
            'month':'十二月',
            'title':'射手'
        },
        {
            'month':'',
            'title':'星座密码'
        }
    ];

    $scope.isRotate=false;
    setTimeout(function(){
        $scope.isRotate=true;
        $scope.$digest();
    },500);
    $scope.rotate=function($index){
        if($index==12){
            $scope.isRotate=!$scope.isRotate;
        }
    }
}]);
